services:
  web:
    build: .
    container_name: KerroScraper
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app/app # This is the critical change to prevent interference
    restart: unless-stopped